name: build-linux
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential cmake pkg-config \
            libboost-all-dev ocl-icd-opencl-dev

      # Guard Windows.h includes (non-destructive patch in CI only)
      - name: Guard Windows.h includes (Linux only)
        shell: bash
        run: |
          set -euo pipefail
          shopt -s nullglob
          for d in AutoDock-Vina-GPU-2.1 QuickVina-W-GPU-2.1 QuickVina2-GPU-2.1; do
            # handle both Windows.h and windows.h, in .h/.hpp/.cpp
            for f in $(grep -RIl --include='*.h' --include='*.hpp' --include='*.cpp' -E '#include\s*<([Ww]indows\.h)>' "$d" || true); do
              awk '
                BEGIN { patched=0 }
                {
                  if ($0 ~ /^[[:space:]]*#include[[:space:]]*<([Ww]indows\.h)>/ && patched==0) {
                    print "#if defined(_WIN32) || defined(WIN32) || defined(WINDOWS)"
                    print $0
                    print "#else"
                    print "#include <cstring>  // shim for Linux CI"
                    print "#endif"
                    patched=1
                  } else {
                    print
                  }
                }
              ' "$f" > "$f.patched" && mv "$f.patched" "$f"
            done
          done
    

      - name: Build AutoDock-Vina-GPU-2.1
        shell: bash
        run: |
          ulimit -s 8192
          cmake -S AutoDock-Vina-GPU-2.1 -B build-av -DCMAKE_BUILD_TYPE=Release
          cmake --build build-av --config Release -j

      - name: Build QuickVina-W-GPU-2.1
        shell: bash
        run: |
          ulimit -s 8192
          cmake -S QuickVina-W-GPU-2.1 -B build-qvw -DCMAKE_BUILD_TYPE=Release
          cmake --build build-qvw --config Release -j

      - name: Build QuickVina2-GPU-2.1
        shell: bash
        run: |
          ulimit -s 8192
          cmake -S QuickVina2-GPU-2.1 -B build-qv2 -DCMAKE_BUILD_TYPE=Release
          cmake --build build-qv2 --config Release -j

      - name: Collect & hash
        shell: bash
        run: |
          mkdir -p dist/linux
          cp build-av/AutoDock-Vina-GPU-2.1 dist/linux/ || cp build-av/Release/AutoDock-Vina-GPU-2.1 dist/linux/
          cp build-qvw/QuickVina-W-GPU-2.1 dist/linux/ || cp build-qvw/Release/QuickVina-W-GPU-2.1 dist/linux/
          cp build-qv2/QuickVina2-GPU-2.1 dist/linux/ || cp build-qv2/Release/QuickVina2-GPU-2.1 dist/linux/
          (cd dist/linux && sha256sum * > SHA256SUMS.txt)

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vina-gpu-2.1-linux-x86_64
          path: dist/linux/**
