name: build-linux
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential cmake pkg-config \
            libboost-all-dev ocl-icd-opencl-dev

      # Wrap any unconditional #include <Windows.h> / <windows.h> so Linux can compile
      - name: Guard Windows.h includes (Linux only)
        shell: bash
        run: |
          set -euo pipefail
          shopt -s nullglob
          for d in AutoDock-Vina-GPU-2.1 QuickVina-W-GPU-2.1 QuickVina2-GPU-2.1; do
            # Replace any line that includes Windows.h (any case, any leading whitespace)
            # with a guarded block. This is CI-only; your source tree stays unchanged.
            files=$(grep -RIl --include='*.h' --include='*.hpp' --include='*.cpp' -E '^[[:space:]]*#include[[:space:]]*<([Ww]indows\.h)>' "$d" || true)
            for f in $files; do
              sed -E -i 's@^[[:space:]]*#include[[:space:]]*<([Ww]indows\.h)>@#if defined(_WIN32) || defined(WIN32) || defined(WINDOWS)\n#include <Windows.h>\n#else\n/* no Windows.h on Linux */\n#endif@g' "$f"
            done
          done

      - name: Build AutoDock-Vina-GPU-2.1
        shell: bash
        run: |
          ulimit -s 8192
          cmake -S AutoDock-Vina-GPU-2.1 -B build-av -DCMAKE_BUILD_TYPE=Release
          cmake --build build-av --config Release -j

      - name: Build QuickVina-W-GPU-2.1
        shell: bash
        run: |
          ulimit -s 8192
          cmake -S QuickVina-W-GPU-2.1 -B build-qvw -DCMAKE_BUILD_TYPE=Release
          cmake --build build-qvw --config Release -j

      - name: Build QuickVina2-GPU-2.1
        shell: bash
        run: |
          ulimit -s 8192
          cmake -S QuickVina2-GPU-2.1 -B build-qv2 -DCMAKE_BUILD_TYPE=Release
          cmake --build build-qv2 --config Release -j

      - name: Collect & hash
        shell: bash
        run: |
          mkdir -p dist/linux
          cp build-av/AutoDock-Vina-GPU-2.1 dist/linux/ || cp build-av/Release/AutoDock-Vina-GPU-2.1 dist/linux/
          cp build-qvw/QuickVina-W-GPU-2.1 dist/linux/ || cp build-qvw/Release/QuickVina-W-GPU-2.1 dist/linux/
          cp build-qv2/QuickVina2-GPU-2.1 dist/linux/ || cp build-qv2/Release/QuickVina2-GPU-2.1 dist/linux/
          (cd dist/linux && sha256sum * > SHA256SUMS.txt)

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vina-gpu-2.1-linux-x86_64
          path: dist/linux/**
