name: build-linux
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: |
          set -euo pipefail
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential cmake pkg-config \
            libboost-all-dev ocl-icd-opencl-dev

      # Safety net: make Windows-only bits compile on Linux without touching sources
      - name: Linux compatibility patch (no heredocs)
        shell: bash
        run: |
          set -euo pipefail
          # Stub <Windows.h> so unconditional includes don't fail
          for d in AutoDock-Vina-GPU-2.1 QuickVina-W-GPU-2.1 QuickVina2-GPU-2.1; do
            mkdir -p "$d/OpenCL/inc"
            printf '%s\n' \
            '#ifndef VINA_GPU_LINUX_WINDOWS_H_STUB' \
            '#define VINA_GPU_LINUX_WINDOWS_H_STUB' \
            '/* CI stub for Linux builds */' \
            '#endif' > "$d/OpenCL/inc/Windows.h"
          done
          # Map GetCurrentProcessId() -> getpid() in my_pid.cpp (AV uses it)
          F="AutoDock-Vina-GPU-2.1/lib/my_pid.cpp"
          if [ -f "$F" ] && ! grep -q 'GetCurrentProcessId getpid' "$F"; then
            T="$(mktemp)"
            printf '%s\n' \
            '#if !defined(_WIN32) && !defined(WIN32) && !defined(WINDOWS)' \
            '#include <unistd.h>' \
            '#define GetCurrentProcessId getpid' \
            '#endif' > "$T"
            cat "$F" >> "$T"
            mv "$T" "$F"
          fi

      - name: Build AutoDock-Vina-GPU-2.1
        shell: bash
        run: |
          set -euo pipefail
          ulimit -s 8192
          cmake -S AutoDock-Vina-GPU-2.1 -B build-av -DCMAKE_BUILD_TYPE=Release
          cmake --build build-av --config Release -j

      - name: Build QuickVina-W-GPU-2.1
        shell: bash
        run: |
          set -euo pipefail
          ulimit -s 8192
          cmake -S QuickVina-W-GPU-2.1 -B build-qvw -DCMAKE_BUILD_TYPE=Release
          cmake --build build-qvw --config Release -j

      - name: Build QuickVina2-GPU-2.1
        shell: bash
        run: |
          set -euo pipefail
          ulimit -s 8192
          cmake -S QuickVina2-GPU-2.1 -B build-qv2 -DCMAKE_BUILD_TYPE=Release
          cmake --build build-qv2 --config Release -j

      - name: Collect & hash
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p dist/linux
          cp build-av/AutoDock-Vina-GPU-2.1 dist/linux/ || cp build-av/Release/AutoDock-Vina-GPU-2.1 dist/linux/
          cp build-qvw/QuickVina-W-GPU-2.1 dist/linux/ || cp build-qvw/Release/QuickVina-W-GPU-2.1 dist/linux/
          cp buil
