name: build-windows

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: windows-2022

    env:
      VCPKG_DEFAULT_TRIPLET: x64-windows
      VCPKG_BINARY_SOURCES: "clear;cache,artifact,readwrite"   # use gha artifact cache
      CMAKE_TOOLCHAIN_FILE: ${{ github.workspace }}\vcpkg\scripts\buildsystems\vcpkg.cmake

    steps:
      - uses: actions/checkout@v4

      # vcpkg in MANIFEST mode; speeds up subsequent runs via cache
      - name: Setup vcpkg (manifest mode, with cache)
        uses: lukka/run-vcpkg@v11
        with:
          # Known good commit; change if you need a newer vcpkg
          vcpkgGitCommitId: "06f1db66c3b3d6b0b9e4bc2a8a6a6a1743e5a3a7"

      # Configure & build AutoDock-Vina-GPU-2.1
      - name: Configure AutoDock-Vina-GPU-2.1
        run: >
          cmake -S AutoDock-Vina-GPU-2.1 -B build-av
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_TOOLCHAIN_FILE="${{ env.CMAKE_TOOLCHAIN_FILE }}"
          -DBoost_USE_STATIC_LIBS=OFF
          -DCMAKE_CXX_FLAGS="/I${{ github.workspace }}\shims /DBOOST_TIMER_ENABLE_DEPRECATED /D_SILENCE_EXPERIMENTAL_FILESYSTEM_DEPRECATION_WARNING"

      - name: Build AutoDock-Vina-GPU-2.1
        run: cmake --build build-av --config Release -j 4

      # Configure & build QuickVina2-GPU-2.1
      - name: Configure QuickVina2-GPU-2.1
        run: >
          cmake -S QuickVina2-GPU-2.1 -B build-qv2
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_TOOLCHAIN_FILE="${{ env.CMAKE_TOOLCHAIN_FILE }}"
          -DBoost_USE_STATIC_LIBS=OFF
          -DCMAKE_CXX_FLAGS="/I${{ github.workspace }}\shims /DBOOST_TIMER_ENABLE_DEPRECATED /D_SILENCE_EXPERIMENTAL_FILESYSTEM_DEPRECATION_WARNING"

      - name: Build QuickVina2-GPU-2.1
        run: cmake --build build-qv2 --config Release -j 4

      # Collect binaries and write SHA256 sums
      - name: Collect & hash
        shell: pwsh
        run: |
          $ErrorActionPreference = "Stop"
          New-Item -ItemType Directory -Force -Path dist\windows | Out-Null
          $bins = @(
            "build-av\Release\AutoDock-Vina-GPU-2.1.exe",
            "build-qv2\Release\QuickVina2-GPU-2.1.exe"
          )
          foreach ($b in $bins) {
            if (Test-Path $b) { Copy-Item $b dist\windows\ }
          }
          Push-Location dist\windows
          Get-ChildItem -File | ForEach-Object {
            $h = Get-FileHash -Algorithm SHA256 $_.FullName
            "$($h.Hash)  $($_.Name)"
          } | Set-Content -Path SHA256SUMS.txt
          Pop-Location

      - name: Upload artifacts (windows)
        uses: actions/upload-artifact@v4
        with:
          name: vina-gpu-2.1-windows-x64
          path: dist/windows/**
