name: build-windows
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: windows-2022
    env:
      VCPKG_DEFAULT_TRIPLET: x64-windows
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive   # fetch vcpkg/ submodule

      - name: MSVC dev shell
        uses: ilammy/msvc-dev-cmd@v1

      - name: Setup vcpkg (classic with submodule)
        uses: lukka/run-vcpkg@v10
        with:
          vcpkgDirectory: vcpkg
          runVcpkgInstall: true
          # Keep the format string minimal; no extra flags that the parser chokes on
          runVcpkgFormatString: >
            install boost-program-options:x64-windows
                    boost-filesystem:x64-windows
                    boost-system:x64-windows
                    opencl:x64-windows

      - name: Configure & build AutoDock-Vina-GPU-2.1
        run: |
          cmake -S AutoDock-Vina-GPU-2.1 -B build-av ^
            -DCMAKE_TOOLCHAIN_FILE=%GITHUB_WORKSPACE%\vcpkg\scripts\buildsystems\vcpkg.cmake ^
            -DCMAKE_BUILD_TYPE=Release
          cmake --build build-av --config Release -j

      - name: Configure & build QuickVina-W-GPU-2.1
        run: |
          cmake -S QuickVina-W-GPU-2.1 -B build-qvw ^
            -DCMAKE_TOOLCHAIN_FILE=%GITHUB_WORKSPACE%\vcpkg\scripts\buildsystems\vcpkg.cmake ^
            -DCMAKE_BUILD_TYPE=Release
          cmake --build build-qvw --config Release -j

      - name: Configure & build QuickVina2-GPU-2.1
        run: |
          cmake -S QuickVina2-GPU-2.1 -B build-qv2 ^
            -DCMAKE_TOOLCHAIN_FILE=%GITHUB_WORKSPACE%\vcpkg\scripts\buildsystems\vcpkg.cmake ^
            -DCMAKE_BUILD_TYPE=Release
          cmake --build build-qv2 --config Release -j

      - name: Collect & hash
        shell: bash
        run: |
          mkdir -p dist/windows
          cp build-av/Release/AutoDock-Vina-GPU-2.1.exe dist/windows/ || true
          cp build-qvw/Release/QuickVina-W-GPU-2.1.exe dist/windows/ || true
          cp build-qv2/Release/QuickVina2-GPU-2.1.exe dist/windows/ || true
          cd dist/windows
          : > SHA256SUMS.txt
          for f in *.exe; do
            if [ -f "$f" ]; then
              powershell -Command "Get-FileHash -Algorithm SHA256 '$f' | ForEach-Object { '\\' + $_.Hash + '  ' + '$f' }" >> SHA256SUMS.txt
            fi
          done

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: vina-gpu-2.1-windows-x64
          path: dist/windows/**
